### ISSUE TITLE
Where is my Money ?

### ISSUE THREAD

**Issue by TrimeGeld** [dogefatherBSC/dogefatherBSC#2]
Why can I how much $ I have got in my Wallet ?

![Bildschirmfoto 2021-05-08 um 11 11 06](https://user-images.githubusercontent.com/78798836/117536480-88b2bf80-affb-11eb-9f27-a2b565a29688.png)

**Comment by dogefatherBSC** [comment]
You can check its value on CoinGecko, PancakeSwap, or PooCoin.

**Comment by TrimeGeld** [comment]
No, that is not 
I need my money in my Wallet see
